try:
    10 / 0
except:
    print('error')

try:
    10 / 0
    # 例外を補足して変数に格納
except ZeroDivisionError as e:
    print(e)
except ZeroDivisionError as e:
    print(e)
